reviewsite/movies/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^index/', views.index, name="index"),
    url(r'^about-movie/(?P<pk>\d+)', views.about_movie),
    url(r'^login/', views.login_view, name='login'),
    url(r'^logout/', views.logout_view),
    url(r'^register/', views.register_view),
    url(r'^movies-rud/(?P<pk>\d+)', views.MovieRudView.as_view(), name="movies-rud"),
    url(r'^movies-cl/', views.MoviesCreateView.as_view(), name="movies-cl"),
    url(r'^post-review/', views.post_reviews, name="post-reviews"),
    url(r'^add_movie', views.add_movie, name="add-movie")
]

reviewsite/reviewsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^movies/', include("movies.urls")),
]

reviewsite/movies/models.py
from django.db import models
from django.conf import settings
from django.db.models import Avg


BASR_DIR = settings.BASE_DIR


def user_directory_path(instance, filename):
    return "movies/static/img/movies/{0}".format(instance.title)


# Create your models here.
class MovieModel(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    release_date = models.DateField()
    image = models.FileField(upload_to=user_directory_path,
                             default="portal/static/img/default-movie.jpg")
    trailer = models.URLField()
    synopsis = models.TextField(max_length=1000)
    movie_rating = models.DecimalField(max_digits=3,
                                       decimal_places=2,
                                       null=True)
    
    def __str__(self):
        return str(self.user.username)

    @property
    def owner(self):
        return self.user


class MovieReview(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="user", on_delete=models.CASCADE)
    movie = models.ForeignKey(MovieModel, related_name="reviews", on_delete=models.CASCADE)
    review_title = models.CharField(max_length=100)
    review = models.TextField(max_length=1000)
    rating = models.IntegerField(null=False)
    time = models.DateField(auto_now=True)
    
    def save(self, *args, **kwargs):
        super(MovieReview, self).save(*args, **kwargs)
        movie_obj = MovieReview.objects.filter(movie=self.movie).first()
        movie_reviews_obj = MovieReview.objects.filter(movie=self.movie).aggregate(Avg('rating'))
        
        save_obj = MovieModel.objects.get(title=movie_obj.movie.title)
        save_obj.movie_rating = movie_reviews_obj["rating__avg"]
        save_obj.save()
        return save_obj

reviewsite/movies/forms.py
from django import forms
from django.contrib.auth import (authenticate, get_user_model, login, logout)
from .models import MovieModel


UserModel = get_user_model()


class UserLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': "form-control", "placeholder": "Email address"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': "form-control", "placeholder": "Password"}))

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")

        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError("This User does not exist")
            elif not user.check_password(password):
                raise forms.ValidationError("Password is incorrect")

            """
            if not user.is_active():
                raise forms.ValidationError("User is not active.")
            """
        return super(UserLoginForm, self).clean(*args, **kwargs)


class UserRegistraionForm(forms.ModelForm):
    username = forms.CharField(required=True,
                               widget=forms.TextInput(attrs={'class': "form-control", "placeholder": "Username"}))
    password = forms.CharField(required=True,
                               widget=forms.PasswordInput(attrs={'class': "form-control", "placeholder": "Password"}))
    re_password = forms.CharField(required=True,
                                  widget=forms.PasswordInput(attrs={'class': "form-control",
                                                                    "placeholder": "Re-enter the Password"}))
    email = forms.EmailField(required=True,
                             widget=forms.TextInput(attrs={'class': "form-control", "placeholder": "Email Address"}))

    class Meta:
        model = UserModel
        fields = [
            "username",
            "email",
            "password",
        ]

    def clean(self, *args, **kwargs):
        password = self.cleaned_data.get("password")
        re_password = self.cleaned_data.get("re_password")
        email = self.cleaned_data.get("email")
        if not password == re_password:
            raise forms.ValidationError("Password does not match")
        email_qs = UserModel.objects.filter(email=email)
        if email_qs.exists():
            raise forms.ValidationError("This email already is use")
        return super(UserRegistraionForm, self).clean(*args, **kwargs)


class MoviesAddForm(forms.ModelForm):
    title = forms.CharField(required=True,
                            widget=forms.TextInput(attrs={'class': "form-control", "placeholder": "Movie Title"}))
    trailer = forms.CharField(required=True,
                              widget=forms.TextInput(attrs={'class': "form-control", "placeholder": "Trailer URL"}))
    release_date = forms.CharField(widget=forms.TextInput(attrs={'class': "form-control", "placeholder": "Release Date", "type": "date"}))
    image = forms.ImageField(widget=forms.FileInput())
    synopsis = forms.CharField(required=True,
                               widget=forms.Textarea(attrs={'class': "form-control", "placeholder": "About Movie"}))
    class Meta:
        model = MovieModel
        fields = [
            "title",
            "trailer",
            "release_date",
            "image",
            "synopsis"
        ]

reviewsite/movies/views.py
from rest_framework.generics import (
    RetrieveUpdateDestroyAPIView,
    ListAPIView
)
from rest_framework.mixins import (
    CreateModelMixin
)
from rest_framework.response import Response
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.db.models import Q
from .forms import UserLoginForm, UserRegistraionForm, MoviesAddForm
from .permissions import IsOwnerOrReadOnly
from .serializers import MoviePostSerializer
from .models import MovieModel, MovieReview
from django.contrib.auth import (authenticate, get_user_model, login, logout)
from django.views.decorators.csrf import csrf_exempt
# Create your views here.
UserModel = get_user_model()


def index(request):
    data = {"user_auth": request.user.is_authenticated()}
    try:
        if request.session["admin"]:
            data["admin"] = True
    except:
        pass

    return render(request, "pages/index.html", data)


def about_movie(request, pk):
    data = {"user_auth": request.user.is_authenticated(),
            "id": pk,
            "form": UserLoginForm}

    try:
        if request.session["admin"]:
            data["admin"] = True
    except:
        pass

    return render(request, "pages/about-movie.html", data)


def login_view(request):
    data = {"title": "Login"}
    form = UserLoginForm(request.POST or None)

    if form.is_valid():
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(username=username, password=password)

        login(request, user)
        if request.user.is_authenticated():
            user_obj = UserModel.objects.filter(username=username).filter(is_staff=True)
            print("Data is ", type(user_obj.count()))
            if user_obj.count() == 1:
                request.session["admin"] = True

            return redirect('index')

    data["form"] = form
    return render(request, "pages/login.html", data)


def logout_view(request):
    request.session["admin"] = False
    logout(request)
    return redirect('index')


def register_view(request):
    data = {"title": "Sign Up"}
    form = UserRegistraionForm(request.POST or None)
    if form.is_valid():
        new_user = form.save(commit=False)
        password = form.cleaned_data.get("password")
        new_user.set_password(password)
        new_user.save()
        return redirect('index')
        
    data["form"] = form
    return render(request, "pages/login.html", data)


@csrf_exempt
def post_reviews(request):
    data = {"success": False,
            "message": "None",
            "data": None}
    if request.method == "POST":
        try:

            user_obj = request.user
            review_title = request.POST.get("title")
            ratings = request.POST.get("rating")
            review = request.POST.get("review")
            pk = request.POST.get("id")

            movie_obj = MovieModel.objects.get(pk=pk)

            review_obj = MovieReview.objects.create(user=user_obj,
                                                    movie=movie_obj,
                                                    review=review,
                                                    review_title=review_title,
                                                    rating=ratings)
            review_obj.save()
            data["message"] = "data saved"
            data["success"] = True
        except Exception as ex:
            data["message"] = "Exception Raised [%s] " % ex
        finally:
            return JsonResponse(data)


def add_movie(request):
    data = {"title": "Add Movie",
            "form": MoviesAddForm,
            "message": None}
    if request.method == "POST":
        form = MoviesAddForm(request.POST,
                             request.FILES)
        if form.is_valid():
            model_instance = form.save(commit=False)
            model_instance.user = request.user
            model_instance.save()
    return render(request, "pages/login.html", data)


########################################################
"""              Api for movie review                """
########################################################


class MoviesCreateView(CreateModelMixin, ListAPIView):
    lookup_field = 'pk'
    serializer_class = MoviePostSerializer
    permission_classes = [IsOwnerOrReadOnly]

    def get_queryset(self):
        qs = MovieModel.objects.all()
        query = self.request.GET.get("q")
        if query is not None:
            qs = qs.filter(
                Q(title__icontains=query)
            ).distinct()
        return qs

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

    def post(self, request, *args, **kwargs):
        try:
            if request.session["admin"]:
                return self.create(request, *args, **kwargs)
            else:
                return Response("user does not have permission for this operation")
        except:
            return Response("user does not have permission for this operation")


class MovieRudView(RetrieveUpdateDestroyAPIView):
    lookup_field = 'pk'
    serializer_class = MoviePostSerializer
    permission_classes = [IsOwnerOrReadOnly]
    def get_queryset(self):
        return MovieModel.objects.all()

reviewsite/movies/templates/pages/about-movie.html
<!DOCTYPE html>
<html lang="en">

{% include "snippets/head.html" %}

  <body id="page-top">
    {% include "snippets/navbar.html" %}
    <header class="bg-primary text-white">
      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-4 text-center">
          <div id="movie-img">
            <img class="img-responsive" src="/static/img/default-movie.jpg" height="60"  width="80" alt="About Movie name">
          </div>
          <div id="movie-title">

          </div>
        </div>
        <div class="col-md-6  text-white">
            <div class="row">
                <div class="col-md-2"><i class="fa fa-cloud"></i> Movie Trailer Link</div>
                <div class="col-md-5" id="movie-trailer"></div>
            </div>
            <div class="row">
                <div class="col-md-2"><i class="fa fa-star"></i> Ratings </div>
                <div class="col-md-5" id="movie-rating"></div>
            </div>
            <div class="row">
                <div class="col-md-2"><i class="fa fa-table"></i> Release Date </div>
                <div class="col-md-5" id="movie-rel"></div>
            </div>
            <div class="row">
                <div class="col-md-2"><i class="fa fa-book"></i> Movie Summary </div>
                <div class="col-md-5" id="movie-summary"></div>
            </div>

        </div>
      </div>
    </header>

    <main role="main" class="container">
      <div class="my-3 p-3 bg-white rounded box-shadow">
        <h6 class="border-bottom border-gray pb-2 mb-0">Reviews</h6>
        <div id="reviews_comment">

        </div>

            <tr>
                <td>
                    <input type="text" name="title" class="form-control" placeholder="Review in short" required id="id_title" />
                </td>
            </tr>
            <tr>
                <td>
                    <input type="number" name="rating" class="form-control" placeholder="Rating" required id="id_rating" />
                </td>
            </tr>
            <tr>
                <td>
                    <textarea name="review" class="form-control" placeholder="Review" id="id_review"></textarea>
                </td>
            </tr>


          <button class="btn btn-lg btn-primary btn-block" onclick="add_comment('{{id}}')">Submit Review</button>


      </div>


    </main>
    {% include "snippets/footer.html" %}

  </body>
<script>
  $(document).ready(function(){
        get_movie_by_id("{{id}}");
    });
</script>
</html>

reviewsite/movies/templates/pages/add-movie.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>{{ title }} Critz </title>

    <!-- Bootstrap core CSS -->
    <link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/css/login.css" rel="stylesheet">
  </head>

  <body class="text-center">
    <form class="form-signin" method="post" enctype=multipart/form-data>
        {% csrf_token %}
      <img class="mb-4" src="/static/img/login.png" alt="" width="72" height="72">
      <h1 class="h3 mb-3 font-weight-normal">{{ title }} Form</h1>
        {{ form}}
      <div class="checkbox mb-3">

      </div>
      <button class="btn btn-lg btn-primary btn-block" type="submit">{{ title }}</button>

    </form>
  </body>
</html>

reviewsite/movies/templates/pages/index.html
<!DOCTYPE html>
<html lang="en">

{% include "snippets/head.html" %}

  <body id="page-top">
    {% include "snippets/navbar.html" %}
    <header class="bg-primary text-white">
      <div class="container text-center">
        <h1>Welcome to Crit<b>Z</b></h1>
        <p class="lead">A movie review site</p>

          <div class="form-group">
            <input id="movieSearch" type="search" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter movie name">
            <small id="searchMovie" class="form-text .text-primary">Enter movie name and get reviews and post reviews.</small>
          </div>
          <button id="search" class="btn btn-info" onclick="search_movie();">Search Movie</button>

      </div>
    </header>

    <section >
      <div class="container">
        <div class="row" id="bmovies">

        </div>
      </div>
    </section>
    {% include "snippets/footer.html" %}
  </body>
<script>
    $(document).ready(function(){
        get_movies()
    });
    console.log("{{admin}}");
</script>
</html>

reviewsite/movies/templates/pages/login.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>{{ title }} Critz </title>

    <!-- Bootstrap core CSS -->
    <link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/css/login.css" rel="stylesheet">
  </head>

  <body class="text-center">
    <form class="form-signin"  method="POST" enctype="multipart/form-data">
        {% csrf_token %}
      <img class="mb-4" src="/static/img/login.png" alt="" width="72" height="72">

      <h1 class="h3 mb-3 font-weight-normal">{{ title }} Form</h1>
        <a href="/movies/index/">Home</a><br>
        {{ form}}
      <div class="checkbox mb-3">

      </div>
      <button class="btn btn-lg btn-primary btn-block" type="submit">{{ title }}</button>
      <p class="mt-5 mb-3 text-muted">&copy; 2017-2018</p>
    </form>
  </body>
<script>


</script>
</html>

reviewsite/movies/templates/pages/template.html
<!DOCTYPE html>
<html lang="en">

{% include "snippets/head.html" %}

  <body id="page-top">
    {% include "snippets/navbar.html" %}
    <header class="bg-primary text-white">
      <div class="row">
          <div class="col-md-4">
              <img src="/static/img/default.jpg">
          </div>
        
      </div>
    </header>

    <section>
      
    </section>
    {% include "snippets/footer.html" %}

  </body>

</html>